spring.application.name=platform

spring.datasource.url=jdbc:postgresql://localhost:5432/itech_db

#Credenciales de mi cuenta postgreeSQL
spring.datasource.username=postgres
spring.datasource.password=admin

#Despues se hace una configuracion de HIBERNATE y JPA el cual es el estandar de la industria
spring.jpa.hibernate.ddl-auto=update

#Con fines pedagogicos y educativos se muestra por consola las consultas de SQL que  
# SPRING-BOOT hace por debajo para visualizar mejor el proceso

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format-sql=true

